### ISSUE TITLE
[Android Bootcamp] Project 2: Instagram Viewer - Ready for Review

### ISSUE THREAD

**Issue by lwhsu** [lwhsu/InstagramViewer#1]
My app is complete, please review.
Thanks!

/cc @nidhi1608 @thecodepath

Li-Wen Hsu lwhsu@yahoo-inc.com

**Comment by nidhi1608** [comment]
:+1: Looks good overall. I have provided a detailed [Feedback Guide here](https://gist.github.com/nesquena/67a195af43a981f3827d) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Hopefully this first project has given you a better sense of working with RelativeLayout which is a very flexible layout system. This assignment also gave us our first introduction to networking, working with APIs and loading remote images. The next assignment will introduce new concepts such as accepting user input and navigating between activities and will also reinforce important concepts such as networking, using APIs, handling remote images.

Let us know if you have any other thoughts or questions about this assignment.
